In [1]:
import numpy as np

array creation

In [ ]:
np.array()
np.zeros()
np.ones()
np.arange()
np.linspace()
np.random.rand()
np.random.randint()

In [ ]:
arr = np.array([1,2,3,9,0,5])
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr2)

[1 2 3 9 0 5]


In [9]:
arr00 = np.zeros(5)
arr0 = np.zeros((2,4))
print(arr0)
print(arr00)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
