In [46]:
import numpy as np

## Matrix Multiplication

In [47]:
arr = np.random.rand(12)
arr2 = np.random.rand(12)

In [48]:
arr.reshape(3, 4)
arr2.reshape(3, 4)

array([[0.51231119, 0.48025981, 0.9366147 , 0.17072448],
       [0.39801096, 0.11253986, 0.79299525, 0.76711089],
       [0.47358598, 0.90254107, 0.51821389, 0.31465339]])

In [49]:
mul = arr @ arr2
mul

np.float64(2.2745085277276758)

In [50]:
np.dot(arr, arr2)

np.float64(2.2745085277276758)

## Example 2

In [51]:
A = np.arange(1, 10)
A = A.reshape(3,3)

In [52]:
B = np.arange(11, 20)
B = B.reshape(3,3)

In [53]:
A @ B

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [54]:
C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])

C @ D

array([[19, 22],
       [43, 50]])