In [1]:
import numpy as np

In [ ]:
# create from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d.shape)
print(arr_2d) 

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr1 = np.zeros((2,3), dtype="int64")
print(arr1)
print(arr1.shape) 
print(arr1.dtype)

[[0 0 0]
 [0 0 0]]
(2, 3)
int64


In [15]:
arr2 = np.ones((2,3), dtype="int64")
print(arr2)
print(arr2.shape) 
print(arr2.dtype)

[[1 1 1]
 [1 1 1]]
(2, 3)
int64


In [16]:
arr3 = np.full((3,4), 1000)
print(arr3)
print(arr3.shape) 
print(arr3.dtype)

[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]]
(3, 4)
int64


In [18]:
# identity matrix
arr4 = np.eye((5))
print(arr4)
print(arr4.shape) 
print(arr4.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
float64


In [21]:
arr5 = np.arange(1, 50, 5)
print(arr5, arr5.shape, arr5.dtype)

[ 1  6 11 16 21 26 31 36 41 46] (10,) int64
