# Practise - 1

### 1. Create an array from 1 to 20

### 2. Find all even numbers

### 3. Multiply all values by 5

### 4. Reshape into 4 rows

### 5. Find the mean

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
even = arr[arr %2 == 0]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
mul = arr * 5
mul

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [5]:
arr.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
arr.mean()

np.float64(10.5)

# Practice - 2
### Create a random dataset

### Select values > 50

### Find maximum

### Find minimum

### Reshape to 5x5

In [7]:
import numpy as np

In [22]:
rng = np.random.default_rng()
rand = rng.integers(low=1, high= 100, size= 5) 
rand

array([49, 75,  1, 29, 20])

In [9]:
gt50 = rand[rand>50]
gt50

array([68, 63, 94, 54, 79, 68, 60, 61, 80, 68, 88, 56, 61, 62, 84, 93, 86])

In [10]:
max = rand.max()
max

np.int64(94)

In [11]:
min = rand.min()
min

np.int64(1)

In [12]:
rand.reshape(5, 5)

array([[68, 46, 11, 38, 63],
       [94, 54,  1, 10,  3],
       [79, 44, 68, 60, 61],
       [80, 68, 88, 56, 61],
       [33, 62, 84, 93, 86]])

# Practice - 3

### Find average score per student
### Find highest score
### Find students scoring above 80 average
### Reshape data
### Multiply scores by bonus marks

In [13]:
import numpy as np

In [14]:
# demo data
scores = np.array([[85, 90, 78], [65, 70, 80], [95, 88, 92]])

In [15]:
avg_score = scores.mean()
avg_score

np.float64(82.55555555555556)

In [16]:
scores.max()

np.int64(95)

In [17]:
scores[scores>80]

array([85, 90, 95, 88, 92])

In [18]:
scores.reshape(1,9)

array([[85, 90, 78, 65, 70, 80, 95, 88, 92]])

In [19]:
scores * 3

array([[255, 270, 234],
       [195, 210, 240],
       [285, 264, 276]])