## Practise

### Get scores ≥ 60
### Add 5 bonus marks to everyone
### Calculate the average
### Reshape into a 2×3 array

In [2]:
import numpy as np

In [3]:
scores = np.array([45, 60, 75, 30, 90, 55])

In [4]:
score60 = scores[scores>=60]
score60

array([60, 75, 90])

In [5]:
# 5 bonus mark
bonus = scores + 5
bonus

array([50, 65, 80, 35, 95, 60])

In [6]:
# average

mean = scores.mean()
mean

np.float64(59.166666666666664)

In [7]:
# reshape
reshape = scores.reshape(2,3)
reshape

array([[45, 60, 75],
       [30, 90, 55]])