In [55]:
import numpy as np

In [56]:
# Create a NumPy array containing numbers from 1 to 20.
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
# Create an array of 15 zeros.
arr0 = np.zeros(15)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
# Create an array of 10 ones.
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
# Create 12 equally spaced numbers between 5 and 50.


### part 2

In [60]:
arr = np.arange(24)

In [61]:
arr.shape

(24,)

In [62]:
arr.ndim

1

In [63]:
arr.size

24

In [64]:
arr.dtype

dtype('int64')

In [65]:
# reshape
arr.reshape(2, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### part 3

In [66]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
arr[0:5]
arr[-5:]

array([16, 17, 18, 19, 20])

In [68]:
arr[5:12]

array([ 6,  7,  8,  9, 10, 11, 12])

### Boolean Filtering

In [69]:
scores = np.array([45,82,61,90,55,72,39,99])

In [72]:
scores[scores>70]
scores[scores<60]
scores[(scores>50) & (scores<80)]

array([61, 55, 72])

In [78]:
scores.mean()
scores.max()
scores.min()
scores.sum()
scores.std()

np.float64(20.139746150336652)