# Practise - 1

### 1. Create an array from 1 to 20

### 2. Find all even numbers

### 3. Multiply all values by 5

### 4. Reshape into 4 rows

### 5. Find the mean

In [49]:
import numpy as np

In [50]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
even = arr[arr %2 == 0]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
mul = arr * 5
mul

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [53]:
arr.reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
arr.mean()

np.float64(10.5)

# Practice - 2
### Create a random dataset

### Select values > 50

### Find maximum

### Find minimum

### Reshape to 5x5

In [55]:
import numpy as np

In [56]:
rng = np.random.default_rng()
rand = rng.integers(low=1, high= 100, size= 25) 
rand

array([19, 83, 11, 28, 91, 88, 68, 76, 12, 85, 28, 77, 69, 33, 17, 55, 45,
       52, 76,  3, 34, 94,  7, 54, 11])

In [57]:
gt50 = rand[rand>50]
gt50

array([83, 91, 88, 68, 76, 85, 77, 69, 55, 52, 76, 94, 54])

In [58]:
max = rand.max()
max

np.int64(94)

In [59]:
min = rand.min()
min

np.int64(3)

In [60]:
rand.reshape(5, 5)

array([[19, 83, 11, 28, 91],
       [88, 68, 76, 12, 85],
       [28, 77, 69, 33, 17],
       [55, 45, 52, 76,  3],
       [34, 94,  7, 54, 11]])