## Reshape

In [1]:
import numpy as np

In [17]:
arr = np.array([[1, 2, 3], [12, 14, 16], [8, 9, 10], [16, 20, 24]])
arr
# rarr = arr.reshape(3, 4)
# print(rarr.shape)

array([[ 1,  2,  3],
       [12, 14, 16],
       [ 8,  9, 10],
       [16, 20, 24]])

In [18]:
rarr = arr.reshape(3, 4)
print(rarr)

[[ 1  2  3 12]
 [14 16  8  9]
 [10 16 20 24]]
